[workspace]
authors = ["Elisabeth Maxwell <elisabeth.maxwell@maine.edu>"]
channels = ["conda-forge"]
name = "BIO597-SpatialBiodiversity"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.6.3,<5"
pixi-kernel = ">=0.7.1,<0.8"
pygbif = ">=0.6.6,<0.7"
pandas = ">=3.0.5,<4"
geopandas = ">=1.1.4,<2"
