[project]
site_name = "BIO 597 Spatial Analysis of Biodiversity"
site_url = "https://isaacovercast.github.io/BIO597-SpatialBiodiversity/"
site_description = "Course website for BIO 597 Spatial Analysis of Biodiversity."
site_author = "Isaac Overcast"
docs_dir = "docs"
site_dir = "site"
copyright = "Copyright &copy; 2026 Isaac Overcast"

nav = [
  {"Home" = "index.md"},
  {"Syllabus" = "syllabus.md"},
  {"Schedule" = [
    {"Overview" = "schedule/index.md"},
    {"Week 1 (09/04) - Intro & Geopandas" = "schedule/week-01.md"},
    {"Week 2 (09/11) - Occurrence data" = "schedule/week-02.md"},
    {"Week 3 (09/18)" = "schedule/week-03.md"},
    {"Week 4 (09/25)" = "schedule/week-04.md"},
    {"Week 5 (10/02)" = "schedule/week-05.md"},
    {"Week 6 (10/09)" = "schedule/week-06.md"},
    {"Week 7 (10/16)" = "schedule/week-07.md"},
    {"Week 8 (10/23)" = "schedule/week-08.md"},
    {"Week 9 (10/30)" = "schedule/week-09.md"},
    {"Week 10 (11/06)" = "schedule/week-10.md"},
    {"Week 11 (11/13)" = "schedule/week-11.md"},
    {"Week 12 (11/20)" = "schedule/week-12.md"},
    {"Week 13 (12/04)" = "schedule/week-13.md"},
    {"Week 14 (12/11)" = "schedule/week-14.md"},
    {"Week 15 (12/18) - Final Presentations" = "schedule/week-15.md"}
  ]},
  {"Labs" = [
    {"Week 1 (09/04) - Intro & Geopandas" = [
        {"Git Setup" = "labs/lab-01-GitSetup.md"},
        {"Geopandas Intro" = "labs/Lab01-IntroPython-Geopandas.ipynb"},
    ]},
    {"Week 2 (09/11) - Occurrence data" = "labs/Lab02-pygbif.ipynb"},
  ]},
  {"Assignments" = [
    {"Overview" = "assignments/index.md"},
    {"Week 1 (09/04) - Geopandas" = "assignments/Assignment-01-Geopandas.ipynb"},
    {"Week 2 (09/11) - Occurrence data" = "assignments/Assignment-02-pygbif.ipynb"},
  ]},
  {"Software and Data" = "software-data.md"},
  {"Resources" = "resources.md"},
  {"FAQ" = "faq.md"},
]

[project.markdown_extensions]
admonition = {}
pymdownx.details = {}
pymdownx.superfences = {}
attr_list = {}

[project.theme]
variant = "modern"
features = [
  "navigation.instant",
  "navigation.indexes",
  "toc.follow"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "green"
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "green"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon.admonition]
note = "octicons/tag-16"
abstract = "octicons/checklist-16"
info = "octicons/info-16"
tip = "octicons/squirrel-16"
success = "octicons/check-16"
question = "octicons/question-16"
warning = "octicons/alert-16"
failure = "octicons/x-circle-16"
danger = "octicons/zap-16"
bug = "octicons/bug-16"
example = "octicons/beaker-16"
quote = "octicons/quote-16"
